LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libxbc-$(TARGET_BUILD_VARIANT)
LOCAL_CFLAGS := $(KERNELFLINGER_CFLAGS)

LOCAL_STATIC_LIBRARIES := \
	$(KERNELFLINGER_STATIC_LIBRARIES) \
	libkernelflinger-$(TARGET_BUILD_VARIANT)

LOCAL_C_INCLUDES := $(KERNELFLINGER_LOCAL_PATH) \
                    $(LOCAL_PATH)/include

LOCAL_SRC_FILES := \
	libxbc.c 

include $(BUILD_EFI_STATIC_LIBRARY)
